logging:
  level:
    org.springframework.data.r2dbc: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://postgres:5432/customers_db?schema=accounts_schema}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    properties:
      schema: accounts_schema
      sslMode: disable
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 9061
